components/framework/serverless.js

Addresses: https://github.com/serverless/compose/issues/18

fix: Keep `ServerlessDeploymentBucketName` in outputs

---

package.json
src/ComponentsService.js
src/Context.js
src/cli/output.js
src/utils/telemetry/send.js
test/unit/src/components-service.test.js

Closes: https://github.com/serverless/compose/issues/15
I've changed the approach a little bit in comparison to the proposal - instead of storing metadata at state level it is currently filtered out by the specific fields (filtering on state-level turned out to be quite cumbersome when it comes to representing state so I decided it's maybe not the best idea). In the future, I think we need to consider invoking `info` for each component separately for example and representing data this way - I think each component author should have a say on what data they want to expose in such command (it's definitely not going to be all outputs all the time).
btw - I've left the region because otherwise we might end up with 0 outputs to actually show in case of very simple services and I think we have …

Simplify outputs from `info` command + minor formatting cleanup

---

README.md
components/framework/serverless.js
src/Component.js
src/ComponentsService.js
src/index.js
src/render-help.js
test/unit/components/framework/index.test.js

Support refreshing outputs. At the moment, it expects the components to implement the `refreshOutputs` method, however, we might need to reconsider that when we have components that will need to rely on external state
Closes: #45

feat: Introduce `refresh-outputs` command

---

src/Component.js
src/ComponentsService.js
src/handle-error.js
src/index.js
test/unit/src/components-service.test.js

This builds on #58 to format error messages consistently:
- always start with an upper case (because now  `Error:` is on a different line)
- quote all variables/names with `"`
- rewrite some messages to make them more actionable

feat: Format error messages in a consistent manner

---

src/ComponentsService.js
src/handle-error.js
src/index.js

Addresses part of #62 
In order to [minimize wtf/minutes](https://www.osnews.com/story/19266/wtfsm/), this PR adds more detailed error messages for unknown global commands.
There are also specific messages for popular Framework commands, for example "package" or "offline", which we could expect users to run.
Finally, it also detects global CLI options we don't support yet (`--debug`, `--config` and `--param`).
I started adding more of these checks for CLI options of global commands (e.g. deploy, etc.) but I reverted my changes: I think the best way to validate CLI options will be via proper command declaration (via a "command" object), like in Serverless Framework. So I actually think the next step is having proper CLI command validation, instead of quick fixes. I'm not sure if we need to …

Detailed error messages for invalid command and options

---

components/framework/serverless.js
package.json
src/index.js
test/unit/components/framework/index.test.js
test/unit/src/components-service.test.js

Closes: #54 
I've decided to go with the approach where we check before running `exec` for the first time - it's used to actually call `serverless` binary and it will cover all different cases to how the component methods might be called. It's done separately for each component/service because the versions might differ between them.
Few examples of output:
Global parallel command
Global graph-ordered command
Component-specific command

feat: Detect unsupported Framework versions

---

src/configuration/configuration.js
src/index.js
test/unit/src/configuration/configuration.test.js

Addresses #62
Note that since I had to add quite a bit of code for configuration validation, I moved all the configuration-related logic to a dedicated file. That makes `index.js` a bit clearer, but it does produce a large diff here, sorry!

feat: Simple configuration validation

---

src/cli/Output.js
src/render-help.js

I first looked at incorporating Compose help into the Framework help (for the future integration), but I _think_ (let's discuss this a bit later) that still have a full help dedicated to Compose makes sense.
So then I ended up comparing Framework and Compose help and noticed they were formatted slightly differently. I reworked the output to make them more consistent, which simplified it too.

feat: Simplify `--help` to match Framework formatting

---

src/ComponentsService.js

When working on the blog post I realized we never actually shown the app name (compared to original mockups).
Also I switched to `context.appName` to make it consistent, just in case later we somehow process that config option or something 🤷 
Before/After:

feat: Mention app name in the CLI output

---

src/ComponentsService.js
src/cli/Progresses.js

Non-progress error formatting (inline):
In-progress error formatting:
Details in verbose:
I also have a more general question - should we flush all final states of progresses to verbose as well? Currently, we don't do that which might be confusing to users that expect full information in verbose logs cc @mnapoli 
Closes: #53

fix: Improve non-progress errors

---

src/utils/telemetry/store-locally.js

Addresses: #52 
To be consistent with Framework events, compose events themselves are not under high risk for duplication.

refactor: Pass unique id with telemetry events

---

README.md
components/aws-cloudformation/serverless.js
src/Component.js
src/ComponentsService.js
src/Context.js
src/configuration/validate.js
src/index.js
test/unit/components/framework/index.test.js
test/unit/src/components-service.test.js
test/unit/src/configuration/validate.test.js
test/unit/src/utils/telemetry/generate-payload.test.js

Reported internally, remove `name` property as it currently does not serve any meaningful purpose and might cause confustion

refactor: Remove `name` property

---

src/Context.js
src/cli/colors.js
src/handle-error.js
src/index.js
src/render-help.js
src/utils/process-backend-notification-request.js

Use the same color as in Framework - https://github.com/serverless/utils/blob/d5ed2f2639c2e47ca691da0cfd89d09d8bd5028f/lib/log-reporters/node/style.js#L12

refactor: Use single `gray` color in all places

---

src/cli/Progresses.js
src/cli/colors.js

"white" is not a safe color because it doesn't work on white backgrounds. That "white" color was only used in progresses, which explains the screenshot below.
Instead we should have a "no color" kind of color, and it seems chalk.reset is the closest to that.
Before:
After:

fix: Replace white color to support white backgrounds

---

src/index.js
src/validate-options.js
test/unit/src/validate-options.test.js

Closes: #62 
Example error with unsupported options - some of them are recognized as the Framework options

feat: Detect unsupported CLI options and throw

---

components/framework/serverless.js
test/unit/components/framework/index.test.js

fix: Do not duplicate `stage` for Framework-specific commands

---

components/framework/serverless.js
test/unit/components/framework/index.test.js

When investigating https://github.com/serverless/compose/issues/98 I've noticed that we're not handling shorthand options properly for custom Framework commands.

fix: Handling of shorthand options for custom commands

---

components/framework/serverless.js
src/Component.js
src/ComponentContext.js
src/index.js
src/load.js
test/unit/components/framework/index.test.js

The goal is to have a single point where the Compose package and components are coupled. This would be the `ComponentContext` class.
This prepares this work by moving all the component API into `ComponentContext`.

Move all component API into a separate class

---

src/handle-error.js
src/serverless-error.js

1. Log stack traces to verbose for user errors
2. Allow logging the "previous" exception with ServerlessError
I made both of these changes while working on debugging this pattern in #124:
https://github.com/serverless/compose/blob/fa0306ad7ab1b9ab90d4e3cd007e4f8e2f8d684a/src/state/utils/get-compose-s3-state-bucket-name.js#L103-L114
When an error is thrown, for example by the CloudFormation deployment, then it is caught and re-thrown as `ServerlessError`. That gives the following output:
Technically this was a bug, not sure how we can avoid wrapping that in `ServerlessError`, but anyway, that could have happened also with any CloudFormation error.
At this point I had no stack trace to debug. So that's where I added the first commit: log the stack trace to verbose for `ServerlessError`. …

Log better stack traces for errors

---

components/framework/configuration.js
components/framework/index.js
package.json
src/ComponentsService.js
src/configuration/validate.js
src/index.js
src/load.js
test/unit/src/configuration/validate.test.js

Let's discuss this idea this week.
Eventually, we want to validate configuration with JSON schema like in Serverless Framework. But until we have that, the lack of validation will provide a poor user experience for new components.
Related PR that adds JSON schema validation on the website component: https://github.com/serverless/components-core/pull/4

Validate component inputs via JSON schema

---

components/framework/index.js
src/configuration/validate.js
test/unit/components/framework/index.test.js
test/unit/src/configuration/validate.test.js

The following constraint:
- `path` is required
- `path` cannot be `.`
Only apply to Framework services. They shouldn't apply to other components.
The only downside here is that validation of these rules will happen when each Framework component is instantiated (unfortunately).
[SF-18](https://serverlessinc.atlassian.net/browse/SF-18)

Move `path` validation in the Framework component

---

src/cli/Progresses.js

fix: Remove unneeded index from progress footer

---

components/framework/index.js
src/ComponentsService.js
src/validate-options.js
test/unit/components/framework/index.test.js

This PR adds the ability to run `serverless package` in the context of `serverless compose`.
The context for why this is a useful addition: https://serverless-contrib.slack.com/archives/CA4QT5VU3/p1658415216244289
Copy of slack message:
```
[Chris Hinds]
[Yesterday at 3:53 PM]
Is there any way yet to just run package using serverless compose? i.e. one single command to package all services in the compose file
2 replies
[Chris Hinds]
[18 hours ago]
For context as to why this would be useful. We currently run snapshot test and running the serverless package command which allows us to snapshot the outputted cloudformation.
We are also using serverless compose and would like to start using the params option within compose so we can pass params between services and create necessary …
```

feat: Add `package` command
